Script started on Thu 25 Nov 2010 03:12:31 PM MST
bash: .git-completion.bash: No such file or directory
]0;andrew@mylaptop: ~/code/workspace/MOL/colappandrew@mylaptop:~/code/workspace/MOL/colapp master $ sh logfile.log [K[K[K[K[K[K[K[K[K[K[K[Kupload.sh 
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.151630
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.151630.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9999 entites total, 0 previously transferred
[INFO    ] 9999 entities (18013297 bytes) transferred in 498.9 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.152449
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.152449.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9999 entites total, 0 previously transferred
[INFO    ] 9999 entities (18718602 bytes) transferred in 500.6 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.153310
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.153310.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[INFO    ] Unexpected thread death: WorkerThread-2
[INFO    ] An error occurred. Shutting down...
[ERROR   ] Error in WorkerThread-0: <urlopen error [Errno -2] Name or service not known>
[ERROR   ] Error in WorkerThread-2: <urlopen error [Errno -2] Name or service not known>
[ERROR   ] Error in WorkerThread-3: <urlopen error [Errno -2] Name or service not known>
[ERROR   ] Error in WorkerThread-4: <urlopen error [Errno -2] Name or service not known>

[INFO    ] 4055 entites total, 0 previously transferred
[INFO    ] 3530 entities (5947095 bytes) transferred in 240.7 seconds
[INFO    ] Some entities not successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.153711
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.153711.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[ERROR   ] Exception during authentication
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 3175, in Run
    self.request_manager.Authenticate()
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1187, in Authenticate
    remote_api_stub.MaybeInvokeAuthentication()
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 539, in MaybeInvokeAuthentication
    datastore_stub._server.Send(datastore_stub._path, payload=None)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 1161, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.6/urllib2.py", line 1136, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
[INFO    ] Authentication Failed
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.153752
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.153752.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[ERROR   ] Exception during authentication
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 3175, in Run
    self.request_manager.Authenticate()
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1187, in Authenticate
    remote_api_stub.MaybeInvokeAuthentication()
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 539, in MaybeInvokeAuthentication
    datastore_stub._server.Send(datastore_stub._path, payload=None)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 1161, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.6/urllib2.py", line 1136, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
[INFO    ] Authentication Failed
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.153828
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.153828.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9976 entites total, 0 previously transferred
[INFO    ] 9976 entities (17679169 bytes) transferred in 497.1 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.154645
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.154645.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9979 entites total, 0 previously transferred
[INFO    ] 9979 entities (16060361 bytes) transferred in 496.1 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.155502
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.155502.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9979 entites total, 0 previously transferred
[INFO    ] 9979 entities (16739160 bytes) transferred in 496.1 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.160318
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.160318.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9989 entites total, 0 previously transferred
[INFO    ] 9989 entities (16163019 bytes) transferred in 500.4 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.161139
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.161139.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9989 entites total, 0 previously transferred
[INFO    ] 9989 entities (16826278 bytes) transferred in 497.8 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.161958
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.161958.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9999 entites total, 0 previously transferred
[INFO    ] 9999 entities (16672262 bytes) transferred in 498.8 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.162817
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.162817.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9999 entites total, 0 previously transferred
[INFO    ] 9999 entities (17402513 bytes) transferred in 499.7 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.163637
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.163637.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 10000 entites total, 0 previously transferred
[INFO    ] 10000 entities (19587779 bytes) transferred in 501.3 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.164459
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.164459.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 10000 entites total, 0 previously transferred
[INFO    ] 10000 entities (19573647 bytes) transferred in 498.6 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.165318
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.165318.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[INFO    ] [WorkerThread-0] Backing off due to errors: 1.0 seconds
.[INFO    ] Resetting backoff to 0.0
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 10000 entites total, 0 previously transferred
[INFO    ] 10000 entities (64378495 bytes) transferred in 524.9 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.170203
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.170203.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 10000 entites total, 0 previously transferred
[INFO    ] 10000 entities (52797214 bytes) transferred in 504.8 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.171028
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.171028.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9999 entites total, 0 previously transferred
[INFO    ] 9999 entities (17738105 bytes) transferred in 531.1 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.171920
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.171920.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9999 entites total, 0 previously transferred
[INFO    ] 9999 entities (18504659 bytes) transferred in 499.6 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.172740
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.172740.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9997 entites total, 0 previously transferred
[INFO    ] 9997 entities (16185987 bytes) transferred in 501.4 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.173602
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.173602.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[INFO    ] [WorkerThread-4] Backing off due to errors: 1.0 seconds
.[INFO    ] Resetting backoff to 0.0
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9997 entites total, 0 previously transferred
[INFO    ] 9997 entities (16888424 bytes) transferred in 498.7 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.174421
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.174421.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9998 entites total, 0 previously transferred
[INFO    ] 9998 entities (16033581 bytes) transferred in 498.9 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.175240
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.175240.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[INFO    ] [WorkerThread-1] Backing off due to errors: 1.0 seconds
.[INFO    ] Resetting backoff to 0.0
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9998 entites total, 0 previously transferred
[INFO    ] 9998 entities (16749781 bytes) transferred in 560.4 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.180201
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.180201.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[INFO    ] [WorkerThread-0] Backing off due to errors: 1.0 seconds
.[INFO    ] Resetting backoff to 0.0
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9994 entites total, 0 previously transferred
[INFO    ] 9994 entities (16203708 bytes) transferred in 498.6 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.181020
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.181020.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9994 entites total, 0 previously transferred
[INFO    ] 9994 entities (17036841 bytes) transferred in 498.8 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.181839
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.181839.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[INFO    ] [WorkerThread-4] Backing off due to errors: 1.0 seconds
.[INFO    ] Resetting backoff to 0.0
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9992 entites total, 0 previously transferred
[INFO    ] 9992 entities (16265596 bytes) transferred in 499.9 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.182659
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.182659.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9992 entites total, 0 previously transferred
[INFO    ] 9992 entities (17094947 bytes) transferred in 497.8 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.183518
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.183518.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9995 entites total, 0 previously transferred
[INFO    ] 9995 entities (16747098 bytes) transferred in 497.7 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.184336
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.184336.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[INFO    ] [WorkerThread-3] Backing off due to errors: 1.0 seconds
.[INFO    ] Resetting backoff to 0.0
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9995 entites total, 0 previously transferred
[INFO    ] 9995 entities (17666346 bytes) transferred in 498.8 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.185155
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.185155.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9991 entites total, 0 previously transferred
[INFO    ] 9991 entities (16770266 bytes) transferred in 498.4 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.190014
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.190014.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9991 entites total, 0 previously transferred
[INFO    ] 9991 entities (17638010 bytes) transferred in 502.7 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.190837
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.190837.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9999 entites total, 0 previously transferred
[INFO    ] 9999 entities (16992094 bytes) transferred in 498.8 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.191656
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.191656.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9999 entites total, 0 previously transferred
[INFO    ] 9999 entities (17834767 bytes) transferred in 499.5 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.192516
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.192516.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9999 entites total, 0 previously transferred
[INFO    ] 9999 entities (17045348 bytes) transferred in 498.7 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.193335
[INFO    ] Th..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[INFO    ] 9999 entites total, 0 previously transferred
[INFO    ] 9999 entities (17045348 bytes) transferred in 498.7 seconds
[INFO    ] All entities successfully transferred
../../../google_appengine/appcfg.py:42: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  os.path.join(DIR_PATH, 'lib', 'django'),
/home/andrew/code/google_appengine/google/appengine/tools/dev_appserver_login.py:33: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
Application: mol-apps; version: 0-1.
Uploading data records.
[INFO    ] Logging to bulkloader-log-20101125.193335
[INFO    ] Throttling transfers:
[INFO    ] Bandwidth: 250000 bytes/second
[INFO    ] HTTP connections: 8/second
[INFO    ] Entities inserted/fetched/modified: 20/second
[INFO    ] Batch Size: 5
[INFO    ] Opening database: bulkloader-progress-20101125.193335.sql3
[INFO    ] Connecting to mol-apps.appspot.com/remote_api
[INFO    ] Starting import; maximum 5 entities per post
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appenginm
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", ngine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-4] Backing off due to errors: 1.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
   line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 2.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 4.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_aponse)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 4.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 8.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrewTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 16.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 32.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 64.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 128.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 256.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 512.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 1024.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 2048.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 4096.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 8192.0 seconds
[ERROR   ] Retrying on non-fatal HTTP error: 503 Service Unavailable
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/home/andrew/code/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 16384.0 seconds
[ERROR   ] Retrying on non-fatal datastore error: The API call datastore_v3.Put() required more quota than is available.
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 176, in _MakeRealSyncCall
    raise pickle.loads(response_pb.exception().contents())
OverQuotaError: The API call datastore_v3.P Unavailable
[INFO    ] [WorkerThread-2] Backing off due to errors: 16384.0 seconds
[ERROR   ] Retrying on non-fatal datastore error: The API call datastore_v3.Put() required more quota than is available.
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 176, in _MakeRealSyncCall
    raise pickle.loads(response_pb.exception().contents())
OverQuotaError: The API call datastore_v3.Put() required more quota than is available.
[INFO    ] [WorkerThread-2] Backing off due to errors: 32768.0 seconds
[ERROR   ] Retrying on non-fatal datastore error: The API call datastore_v3.Put() required more quota than is available.
Traceback (most recent call last):
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/home/andrew/code/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 291, in Put
    'datastore_v3', 'Put', req, datastore_pb.PutResponse(), rpc)
  File "/home/andrew/code/google_appengine/google/appengine/api/datastore.py", line 195, in _MakeSyncCall
    rpc.check_success()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 499, in check_success
    self.__rpc.CheckSuccess()
  File "/home/andrew/code/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/home/andrew/code/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 176, in _MakeRealSyncCall
    raise pickle.loads(response_pb.exception().contents())
OverQuotaError: The API call datas